In [3]:
import pandas as pd
import numpy as np

In [4]:
random_array_1 = np.random.randint(10, size=(5,3))
random_array_1

array([[0, 1, 7],
       [6, 3, 5],
       [4, 3, 1],
       [8, 4, 7],
       [2, 8, 8]], dtype=int32)

In [5]:
np.unique(random_array_1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [6]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [7]:
a2 = np.array([[1,2,3,4.5], [5,6,787,8]])
a2

array([[  1. ,   2. ,   3. ,   4.5],
       [  5. ,   6. , 787. ,   8. ]])

In [8]:
a3 = np.array([[
                [1, 2, 3, 4, 5, 6], 
                [7, 8, 9, 10, 11, 12], 
                [13, 14, 15, 16, 17, 18],
                
                [19, 20, 21, 22, 23, 24], 
                [25, 26, 27, 28, 29, 30], 
                [31, 32, 33, 34, 35, 36],
    
               ]])
a3

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]]])

In [9]:
a1[0]

np.int64(1)

In [10]:
a3[0]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [11]:
a2[1]

array([  5.,   6., 787.,   8.])

In [12]:
a3[:2, :2, :2]

array([[[1, 2],
        [7, 8]]])

In [13]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[3, 2, 9, 0, 0],
         [1, 6, 5, 5, 2],
         [0, 6, 7, 4, 3],
         [7, 8, 3, 3, 2]],

        [[2, 9, 3, 5, 7],
         [1, 5, 1, 6, 3],
         [3, 9, 2, 0, 4],
         [9, 7, 4, 0, 7]],

        [[0, 6, 7, 6, 7],
         [0, 0, 9, 7, 7],
         [6, 9, 2, 5, 2],
         [6, 4, 8, 8, 7]]],


       [[[3, 5, 8, 5, 6],
         [6, 5, 4, 9, 4],
         [4, 5, 6, 6, 5],
         [0, 0, 4, 3, 9]],

        [[9, 5, 0, 2, 6],
         [5, 6, 0, 1, 6],
         [4, 2, 8, 6, 7],
         [3, 4, 1, 3, 7]],

        [[2, 5, 2, 1, 4],
         [9, 8, 2, 8, 5],
         [2, 3, 2, 2, 4],
         [1, 8, 9, 3, 4]]]], dtype=int32)

In [14]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [15]:
a4[:, :, :, :2]

array([[[[3, 2],
         [1, 6],
         [0, 6],
         [7, 8]],

        [[2, 9],
         [1, 5],
         [3, 9],
         [9, 7]],

        [[0, 6],
         [0, 0],
         [6, 9],
         [6, 4]]],


       [[[3, 5],
         [6, 5],
         [4, 5],
         [0, 0]],

        [[9, 5],
         [5, 6],
         [4, 2],
         [3, 4]],

        [[2, 5],
         [9, 8],
         [2, 3],
         [1, 8]]]], dtype=int32)

# Arithmetic

In [16]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [17]:
a1 + ones

array([2., 3., 4., 5., 6.])

In [18]:
a1 - ones

array([0., 1., 2., 3., 4.])

In [19]:
a1 * ones

array([1., 2., 3., 4., 5.])

In [20]:
a1 / ones

array([1., 2., 3., 4., 5.])

In [21]:
np.square(a1)

array([ 1,  4,  9, 16, 25])

In [22]:
 np.add(a1, ones)

array([2., 3., 4., 5., 6.])

# Aggregations

In [23]:
list = [1,2,3]
type(list)

list

In [24]:
sum(list)

6

In [25]:
sum(a1)

np.int64(15)

In [26]:
np.sum(a1)

np.int64(15)

# Massive num Array

In [27]:
massive_array = np.random.random(10000)
massive_array.size

10000

In [28]:
massive_array[:10]

array([0.78699272, 0.04972208, 0.76112045, 0.09308524, 0.90557371,
       0.96101481, 0.30183495, 0.43660088, 0.73700869, 0.76607656])

In [29]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

1.04 ms ± 55.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
10.2 μs ± 658 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [30]:
a2

array([[  1. ,   2. ,   3. ,   4.5],
       [  5. ,   6. , 787. ,   8. ]])

In [31]:
a2.mean()

np.float64(102.0625)

In [32]:
np.mean(a2)

np.float64(102.0625)

In [33]:
np.max(a2)

np.float64(787.0)

In [34]:
np.var(a2)

np.float64(67024.27734375)

# Demo of std and var

In [35]:
high_var_array = np.array([1,100,2000,3000])
low_var_array = np.array([2,3,5,6,7])

In [36]:
np.var(high_var_array) , np.var(low_var_array)

(np.float64(1626237.6875), np.float64(3.44))

In [37]:
np.std(high_var_array), np.std(low_var_array)

(np.float64(1275.2402469730948), np.float64(1.8547236990991407))

In [38]:
np.mean(high_var_array)

np.float64(1275.25)

# Change the shape of array

In [39]:
a2.shape

(2, 4)

In [40]:
a3.shape

(1, 6, 6)

In [41]:
new_a2 = a2.reshape(1,6,6)

ValueError: cannot reshape array of size 8 into shape (1,6,6)

In [ ]:
new_a2

In [ ]:
new_a2.shape

In [ ]:
new_a2 * a3

# Transpose

In [ ]:
a2.T

In [ ]:
a.shape

In [ ]:
a2.shape

In [ ]:
a3.shape

In [ ]:
a3

# Dot product

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1, mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
mat1*mat2

# Transpose mat 1

In [ ]:
mat1.T

In [ ]:
mat1

In [ ]:
mat1.T

In [ ]:
mat3 = np.dot(mat1.T, mat2)

In [ ]:
mat3

In [ ]:
mat3.shape

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
mat1.T

# Dot product example 

In [77]:
np.random.seed(0)
sales_amount = np.random.randint(20, size = (5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

# Create a dataFrame weekly sales

In [52]:
weekly_sales = pd.DataFrame(sales_amount, index = ["Mon", "Tues", "Wed", "Thurs" , "Fri"], columns=["Almond butter" , "Peanut butter","Cali butter"])

In [53]:
weekly_sales

Almond butter  Peanut butter  Cali butter
Mon               12             15            0
Tues               3              3            7
Wed                9             19           18
Thurs              4              6           12
Fri                1              6            7

# Create a prices data 

In [54]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

# Create a prices dataFrame

In [55]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns=["Almond butter" , "Peanut butter", "Cali butter"])

In [56]:
butter_prices

Almond butter  Peanut butter  Cali butter
Price             10              8           12

In [57]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [58]:
prices.shape

(3,)

In [59]:
sales_amount.shape

(5, 3)

In [60]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [61]:
sales_amount.T

array([[12,  3,  9,  4,  1],
       [15,  3, 19,  6,  6],
       [ 0,  7, 18, 12,  7]], dtype=int32)

In [62]:
total_sales = np.dot(prices, sales_amount.T)

In [63]:
total_sales

array([240, 138, 458, 232, 142])

# daily sales

In [64]:
butter_prices 

Almond butter  Peanut butter  Cali butter
Price             10              8           12

In [65]:
weekly_sales

Almond butter  Peanut butter  Cali butter
Mon               12             15            0
Tues               3              3            7
Wed                9             19           18
Thurs              4              6           12
Fri                1              6            7

In [66]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [67]:
weekly_sales.T.shape

(3, 5)

In [68]:
daily_sales = np.dot(butter_prices, weekly_sales.T)

In [69]:
daily_sales.shape

(1, 5)

In [70]:
weekly_sales.shape

(5, 3)

In [71]:
weekly_sales["Total ($)"] = daily_sales.T

In [72]:
weekly_sales

Almond butter  Peanut butter  Cali butter  Total ($)
Mon               12             15            0        240
Tues               3              3            7        138
Wed                9             19           18        458
Thurs              4              6           12        232
Fri                1              6            7        142

In [110]:
pc_sales = np.random.randint(100, size=(5, 12))
pc_sales

array([[87, 98, 35, 73, 90, 55, 26, 22, 76, 79, 98, 90],
       [51, 46, 80, 61, 60, 47,  0, 10, 75, 13, 71, 94],
       [ 6, 45, 30, 15, 41, 38, 53, 43, 82,  7, 92, 65],
       [41, 66, 92, 78, 91, 31, 93, 50, 46, 93, 33, 12],
       [96, 80, 66, 72, 10, 90, 27, 56, 65, 64, 69, 88]], dtype=int32)

# Create a dataFrame weekly sales

In [158]:
pc_weekly_sales = pd.DataFrame(
    pc_sales,
    index=["Microsoft", "OPEN-AI", "APPLE", "ROBOTIS", "OTHER"],
    columns=["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
)
pc_weekly_sales

January  February  March  April  May  June  July  August  \
Microsoft       87        98     35     73   90    55    26      22   
OPEN-AI         51        46     80     61   60    47     0      10   
APPLE            6        45     30     15   41    38    53      43   
ROBOTIS         41        66     92     78   91    31    93      50   
OTHER           96        80     66     72   10    90    27      56   

           September  October  November  December  
Microsoft         76       79        98        90  
OPEN-AI           75       13        71        94  
APPLE             82        7        92        65  
ROBOTIS           46       93        33        12  
OTHER             65       64        69        88

In [174]:
pc_price = np.random.randint(100, size=(4))


In [198]:
new_tech_frame = pd.DataFrame([pc_price], 
                              index = ["Price"], 
                              columns = ["One", "Two", "Three", "Four"])
new_tech_frame

One  Two  Three  Four
Price   49   55     24    33

In [199]:
pc_weekly_sales.shape

(5, 12)

In [210]:
new_tech_frame

One  Two  Three  Four
Price   49   55     24    33

In [213]:
new_T = new_tech_frame.T

In [215]:
new_T.shape

(4, 1)

In [217]:
new_tech_vector_expanded = np.random.randint(10, size=(12, 1))

In [218]:
total_price = np.dot(pc_weekly_sales, new_tech_vector_expanded)

In [219]:
total_price

array([[3727],
       [2742],
       [2202],
       [3996],
       [3621]], dtype=int32)

In [221]:
pc_weekly_sales[total_price]

KeyError: "None of [Index([(3727,), (2742,), (2202,), (3996,), (3621,)], dtype='object')] are in the [columns]"