In [40]:
import pandas as pd
import numpy as np

In [41]:
random_array_1 = np.random.randint(10, size=(5,3))
random_array_1

array([[2, 1, 9],
       [7, 5, 6],
       [7, 2, 5],
       [1, 1, 6],
       [5, 4, 2]])

In [42]:
np.unique(random_array_1)

array([1, 2, 4, 5, 6, 7, 9])

In [43]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [44]:
a2 = np.array([[1,2,3,4.5], [5,6,787,8]])
a2

array([[  1. ,   2. ,   3. ,   4.5],
       [  5. ,   6. , 787. ,   8. ]])

In [45]:
a3 = np.array([[
                [1, 2, 3, 4, 5, 6], 
                [7, 8, 9, 10, 11, 12], 
                [13, 14, 15, 16, 17, 18],
                
                [19, 20, 21, 22, 23, 24], 
                [25, 26, 27, 28, 29, 30], 
                [31, 32, 33, 34, 35, 36],
    
               ]])
a3

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]]])

In [46]:
a1[0]

1

In [47]:
a3[0]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [48]:
a2[1]

array([  5.,   6., 787.,   8.])

In [49]:
a3[:2, :2, :2]

array([[[1, 2],
        [7, 8]]])

In [50]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[8, 0, 4, 7, 4],
         [3, 3, 1, 7, 2],
         [0, 9, 6, 1, 6],
         [1, 1, 5, 3, 3]],

        [[3, 3, 9, 0, 0],
         [6, 9, 1, 6, 1],
         [5, 9, 4, 4, 8],
         [3, 6, 3, 4, 8]],

        [[9, 3, 6, 8, 8],
         [0, 9, 3, 3, 1],
         [9, 6, 3, 5, 4],
         [3, 8, 5, 2, 9]]],


       [[[5, 8, 1, 6, 3],
         [7, 6, 7, 9, 1],
         [4, 7, 1, 6, 5],
         [5, 8, 7, 1, 3]],

        [[9, 0, 3, 6, 9],
         [5, 2, 9, 1, 1],
         [5, 4, 3, 8, 3],
         [0, 1, 9, 1, 0]],

        [[1, 3, 5, 9, 6],
         [7, 6, 2, 4, 1],
         [7, 3, 8, 9, 2],
         [1, 5, 0, 1, 6]]]])

In [51]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [52]:
a4[:, :, :, :2]

array([[[[8, 0],
         [3, 3],
         [0, 9],
         [1, 1]],

        [[3, 3],
         [6, 9],
         [5, 9],
         [3, 6]],

        [[9, 3],
         [0, 9],
         [9, 6],
         [3, 8]]],


       [[[5, 8],
         [7, 6],
         [4, 7],
         [5, 8]],

        [[9, 0],
         [5, 2],
         [5, 4],
         [0, 1]],

        [[1, 3],
         [7, 6],
         [7, 3],
         [1, 5]]]])

# Arithmetic

In [53]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [54]:
a1 + ones

array([2., 3., 4., 5., 6.])

In [55]:
a1 - ones

array([0., 1., 2., 3., 4.])

In [56]:
a1 * ones

array([1., 2., 3., 4., 5.])

In [57]:
a1 / ones

array([1., 2., 3., 4., 5.])

In [58]:
np.square(a1)

array([ 1,  4,  9, 16, 25])

In [59]:
 np.add(a1, ones)

array([2., 3., 4., 5., 6.])

# Aggregations

In [60]:
list = [1,2,3]
type(list)

list

In [61]:
sum(list)

6

In [62]:
sum(a1)

15

In [63]:
np.sum(a1)

15

# Massive num Array

In [64]:
massive_array = np.random.random(10000)
massive_array.size

10000

In [65]:
massive_array[:10]

array([0.65021375, 0.52638869, 0.61138342, 0.96893368, 0.71490606,
       0.69868435, 0.32037905, 0.25866375, 0.80651695, 0.75164949])

In [66]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

841 μs ± 39.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
6.71 μs ± 121 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [67]:
a2

array([[  1. ,   2. ,   3. ,   4.5],
       [  5. ,   6. , 787. ,   8. ]])

In [68]:
a2.mean()

102.0625

In [69]:
np.mean(a2)

102.0625

In [70]:
np.max(a2)

787.0

In [71]:
np.var(a2)

67024.27734375

# Demo of std and var

In [72]:
high_var_array = np.array([1,100,2000,3000])
low_var_array = np.array([2,3,5,6,7])

In [73]:
np.var(high_var_array) , np.var(low_var_array)

(1626237.6875, 3.44)

In [74]:
np.std(high_var_array), np.std(low_var_array)

(1275.2402469730948, 1.8547236990991407)

In [75]:
np.mean(high_var_array)

1275.25

# Change the shape of array

In [76]:
a2.shape

(2, 4)

In [77]:
a3.shape

(1, 6, 6)

In [78]:
new_a2 = a2.reshape(1,6,6)

ValueError: cannot reshape array of size 8 into shape (1,6,6)

In [ ]:
new_a2

In [ ]:
new_a2.shape

In [ ]:
new_a2 * a3

# Transpose

In [ ]:
a2.T

In [ ]:
a.shape

In [ ]:
a2.shape

In [ ]:
a3.shape

In [79]:
a3

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]]])

# Dot product

In [81]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [88]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [89]:
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

# Transpose mat 1

In [90]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [98]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [99]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [105]:
mat3 = np.dot(mat1.T, mat2)

In [103]:
mat3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [106]:
mat3.shape

(3, 3)

In [107]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [108]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [109]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

# Dot product example 

In [127]:
np.random.seed(0)
sales_amount = np.random.randint(20, size = (5,3))
sales_amount.shape

(5, 3)

# Create a dataFrame weekly sales

In [112]:
weekly_sales = pd.DataFrame(sales_amount, index = ["Mon", "Tues", "Wed", "Thurs" , "Fri"], columns=["Almond butter" , "Peanut butter","Cali butter"])

In [113]:
weekly_sales

Almond butter  Peanut butter  Cali butter
Mon               12             15            0
Tues               3              3            7
Wed                9             19           18
Thurs              4              6           12
Fri                1              6            7

# Create a prices data 

In [136]:
prices = np.array([10,8,12])
prices


array([10,  8, 12])

# Create a prices dataFrame

In [161]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns=["Almond butter" , "Peanut butter", "Cali butter"])

In [125]:
butter_prices

Almond butter  Peanut butter  Cali butter
Price             10              8           12

In [131]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [132]:
prices.shape

(3,)

In [133]:
sales_amount.shape

(5, 3)

In [137]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [139]:
sales_amount.T

array([[12,  3,  9,  4,  1],
       [15,  3, 19,  6,  6],
       [ 0,  7, 18, 12,  7]])

In [191]:
total_sales = np.dot(prices, sales_amount.T)

In [192]:
total_sales

array([240, 138, 458, 232, 142])

# daily sales

In [193]:
butter_prices 

Almond butter  Peanut butter  Cali butter
Price             10              8           12

In [194]:
weekly_sales

Almond butter  Peanut butter  Cali butter
Mon               12             15            0
Tues               3              3            7
Wed                9             19           18
Thurs              4              6           12
Fri                1              6            7

In [197]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [199]:
weekly_sales.T.shape

(3, 5)

In [211]:
daily_sales = np.dot(butter_prices, weekly_sales.T)

In [213]:
daily_sales.shape

(1, 5)

In [214]:
weekly_sales.shape

(5, 3)

In [215]:
weekly_sales["Total ($)] = daily_sales

SyntaxError: unterminated string literal (detected at line 1) (2370151129.py, line 1)

In [217]:
weekly_sales["Total ($)"] = daily_sales.T

In [218]:
weekly_sales

Almond butter  Peanut butter  Cali butter  Total ($)
Mon               12             15            0        240
Tues               3              3            7        138
Wed                9             19           18        458
Thurs              4              6           12        232
Fri                1              6            7        142